version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./config/nginx/ravelo-apps.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client-ui
    ports:
      - 80:80
      - 443:443
  mongo:
    image: mongo
    restart: always
    container_name: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: user
#      MONGO_INITDB_ROOT_PASSWORD: letmein
    volumes:
      - ./databases/mongodb:/data/db
    ports:
      - 27017:27017
  ravelo-apps-ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ravelo-apps-ui
    volumes:
      - ./services/sarch-marketing-ui:/code
      - /code/node_modules
    depends_on:
      - ims-api
  ravelo-apps-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ims-api
    environment:
      - NODE_ENV=local
    volumes:
      - ./sarch-ims-api:/code
      - /code/node_modules
    depends_on:
      - mongo